apiVersion: v1
kind: ConfigMap
metadata:
  name: purltal-config
  namespace: purltal

data:
  urls.json: |-

    {
        "Event": {
            "Monitoring": [
              { "name":"prometheus" , "link":"https://prometheus.event.dreamhack.se/graph"},
              { "name":"dhmap" , "link":"https://status.event.dreamhack.se/dhmap/dhmon.html"},
              { "name":"buildstatus" , "link":"https://status.event.dreamhack.se/webmon/buildstatus.html"},
              { "name":"grafana" , "link":"https://grafana.event.dreamhack.se"},
              { "name":"dhcpinfo" , "link":"https://dhcpinfo.event.dreamhack.se"},
              { "name":"dnsstat" , "link":"https://dnsstat.event.dreamhack.se"},
              { "name":"vCenter" , "link":"https://vc.event.dreamhack.se"},
              { "name":"alertmanager" , "link":"https://alertmanager.event.dreamhack.se"}
            ]
        },
        "Colo": {
            "Monitoring": [
              { "name":"prometheus" , "link":"https://prom.tech.dreamhack.se"},
              { "name":"prometheus-fed" , "link":"https://prom-fed.tech.dreamhack.se"},
              { "name":"puppet" , "link":"https://puppetboard.tech.dreamhack.se"},
              { "name":"grafana" , "link":"https://grafana.tech.dreamhack.se"},
              { "name":"assets" , "link":"https://assets.tech.dreamhack.se"},
              { "name":"trac" , "link":"https://doc.tech.dreamhack.se/trac"},
              { "name":"svn" , "link":"https://doc.tech.dreamhack.se/svn"},
              { "name":"deploy-ui" , "link":"https://deploy-ui.tech.dreamhack.se"},
              { "name":"vault" , "link":"https://vault.tech.dreamhack.se"},
              { "name":"vCenter" , "link":"https://vc.tech.dreamhack.se"},
              { "name":"alertmanager-sto2" , "link":"https://alert-sto2.tech.dreamhack.se"},
              { "name":"fusion", "link":"https://fusion.tech.dreamhack.se"},
              { "name":"request", "link":"https://request.tech.dreamhack.se/"}
            ]
        },
        "Tools": {
            "tools": [
              { "name":"github" , "link":"https://github.com/dhtech"},
              { "name":"circleci" , "link":"https://circleci.com/gh/dhtech"},
              { "name":"quay" , "link":"https://quay.io/organization/dhtech"},
              { "name":"codeclimate" , "link":"https://codeclimate.com"},
              { "name":"monday", "link": "https://eslfaceitgroup.monday.com/"}
            ]
        }
    }

