apiVersion: v1
kind: ConfigMap
metadata:
  name: fusiondirectory-config
  namespace: ldap

data:
    dhtech-ca.crt: |-

      -----BEGIN CERTIFICATE-----
      MIIFuTCCA6GgAwIBAgIUdBLqnMzdx01VpevSyZaFkYLDUcowDQYJKoZIhvcNAQEL
      BQAwHjEcMBoGA1UEAxMTZGh0ZWNoIFJvb3QgQ0EgLSBSMTAeFw0xODA1MDUyMTIx
      MTRaFw0yODA1MDIyMTIxNDFaMB4xHDAaBgNVBAMTE2RodGVjaCBSb290IENBIC0g
      UjEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCkuaHJKtVa4P3otB5W
      tBpoP37bvx3QzTGx3vw+bAnvw5PIgxDmtVNHpxGqBzQzT2r9ok7Cbu2H+H5lrxgN
      EJc3B7y+3sigjMm6HZ98R1Wgg7O66UK8g4pFCTGmQRyyueZ5aF6rQiIVM1XEYhCu
      myBjp4O2XgSTfOiBGHitFUeEcxMRwpNlNbZRQEeOeJgsGA6fehy4aboEuq71XkON
      6nZxtBIh3H7yFOjlNyftfe1u0QAhzve5Gs4ZNe9A7TpAgn4DpflRAt9sPzvLe4aN
      e64a0FnN5hBagPFGS+IvD0YFh0m7ET4be/rBHwXDcuTO0xTqvLKMGX418n1fBwCy
      aogeuiijLWpI/+/+Zl1AguyhiQ4iYhR1h4S8V8AAkuXbgzP9GJCmcY/m5AF6xe/i
      5SVBnjQANdS2E8b2tzJC3FcsFxHRlk1x8CS6iEOlLKyTx29eMUEKWDqhZ2IiIo76
      B+SteUg92fQPoKQ1owRbKe9dbCSFaLS7qbFGnm+wMTLgfVRt/63tyfGAeMz9r4jQ
      UAD3zp4z8O6qtXcjzX775FGY55K/q2FbVB/W8dEo6rx6sF8NXjDLG3/rQGXcZp2D
      2jhNjT6O9upfqmCH7jz7a617JDClFrUbLr5RQBFTn5JYSS4pMBrlk805TTkBuLw5
      wYT95JJdD5giJ85yaKvc93jTHQIDAQABo4HuMIHrMA4GA1UdDwEB/wQEAwIBBjAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR9r38bDYc0B3pt9FWqt9WCWwKLmTAf
      BgNVHSMEGDAWgBR9r38bDYc0B3pt9FWqt9WCWwKLmTBIBggrBgEFBQcBAQQ8MDow
      OAYIKwYBBQUHMAKGLGh0dHBzOi8vdmF1bHQudGVjaC5kcmVhbWhhY2suc2UvdjEv
      Y2EtcGtpL2NhMD4GA1UdHwQ3MDUwM6AxoC+GLWh0dHBzOi8vdmF1bHQudGVjaC5k
      cmVhbWhhY2suc2UvdjEvY2EtcGtpL2NybDANBgkqhkiG9w0BAQsFAAOCAgEABs5g
      XRz1t5MCccrOqOadRATgc12xwX8qmNVFrQZKLsatOYzdKdJEPf/HfO94f5a4ZFV4
      lzvexq8rZcN/HTub17RgL5fIdsc1FIoT+pR/e2u349Kro9R8aZc1UxvV66gHBEEK
      Fht2Oohzqh0Wwvr7PSle1X2PDC7DJTSOuXaJ7zbrxx0tjKyFuJR9G8wsOS9rZIE3
      /GWjMWHVGXrH9yNF3S15uCRHX9yNJRH9dzM/tXGaZXuIb7qP4bMihC/bjmy7bK83
      7gBP7kVT0ZKQXbUdE2ZCx40K9tOletx9Ce7ii/VrJ5LpbAy5y0RhROaXvgogZxE3
      sUftuDZGGkmHuf5rp7PDHe9zEyrgEPrU7HbKCOH1/k0frj7RRw3dhlkx8xxYUn1y
      jRExaotX42fWv9kmXnlKpf1eLlWybXpSEli9FAdinD+T9VZldB89fNaj5VSWl3o4
      h0Og3RUs7Z5b/M4nw+BSkMhCuKIdBbhwVqv7/4pqTl4Y4mlfpEjR57TQKxpInGyk
      e9VVmvcbxpQohD3ijIZkNw89Qdsrv3me1lgnx60FGEF4BGzxf6+x2X+sFV1jc78Y
      rw3u0s10CJv2pnPgiUwH5aNynSJHxPK5XYkGKAnXyOi9LisrMPJMOVcdKRTGY9zU
      IYU4ZFIi6b+NU3f9h1AjV23vHyXpCbCWPKMLmlw=
      -----END CERTIFICATE-----

