apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-fed-config
  namespace: monitoring

data:
  prometheus.yml: |-

    global:
      scrape_interval:     30s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
           - alertmanager.monitoring


    scrape_configs:
    - job_name: 'event-scraper'

      static_configs:
      - targets: ['prom.event.dreamhack.se:9090']
