---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-fed-ext
  namespace: monitoring
  labels:
    k8s-app: prometheus-fed
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: prometheus-fed
  type: ClusterIP

